export interface Starship {
  name: string,
  model: string,
  manufacturer: string,
  cost_in_credits: 1000000000000,
  length: 120000,
  max_atmosphering_speed: string,
  crew: string,
  passengers: string,
  cargo_capacity: 1000000000000,
  consumables: string,
  hyperdrive_rating: 4.0,
  MGLT: 10,
  starship_class: string,
  pilots: [],
  films: string[],
  created: string,
  edited: string,
  url: string
}
