// ActionTypes STARSHIPS
export const CREATE_STARSHIP = "CREATE_STARSHIP";
export const UPDATE_STARSHIP = "UPDATE_STARSHIP";
export const DELETE_STARSHIP = "DELETE_STARSHIP";
export const FETCH_ALL_STARSHIPS = "FETCH_ALL_STARSHIPS";

// ActionTypes PLANETS
export const CREATE_PLANET = "CREATE_PLANET";
export const UPDATE_PLANET = "UPDATE_PLANET";
export const DELETE_PLANET = "DELETE_PLANET";
export const FETCH_ALL_PLANETS = "FETCH_ALL_PLANETS";

// ActionTypes PEOPLE
export const CREATE_PERSON = "CREATE_PERSON";
export const UPDATE_PERSON = "UPDATE_PERSON";
export const DELETE_PERSON = "DELETE_PERSON";
export const FETCH_ALL_PEOPLE = "FETCH_ALL_PEOPLE";

// ActionTypes APP
export const TOGGLE_DISPLAY = "TOGGLE_DISPLAY";
export const NEW_QUERY = "NEW_QUERY";
